"""
abduction_engine.py — Structured Creative Leap Module

Abduction = inference to the best explanation.
It is the cognitive mode of scientists forming hypotheses,
detectives naming suspects, artists making unexpected connections.

It is NOT random hallucination.
It IS structured confabulation — reasoned leaps with explicit uncertainty.

This engine:
1. Takes known facts and observations
2. Generates candidate explanations ranked by plausibility
3. Flags each with an explicit confidence score
4. Labels all output as speculative
5. Never presents an abductive leap as ground truth

"The game is afoot." — Sherlock Holmes (abduction engine, 1887)
"""

from datetime import datetime
import random


class AbductiveHypothesis:
    """A single candidate explanation generated by the abduction engine."""

    def __init__(self, hypothesis: str, confidence: float, reasoning: str, leap_distance: float):
        self.hypothesis = hypothesis
        self.confidence = round(min(max(confidence, 0.0), 1.0), 3)
        self.reasoning = reasoning
        self.leap_distance = round(min(max(leap_distance, 0.0), 1.0), 3)
        # leap_distance: 0.0 = close to known data, 1.0 = very far out
        self.timestamp = datetime.utcnow().isoformat()

    def to_dict(self) -> dict:
        return {
            "hypothesis": self.hypothesis,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "leap_distance": self.leap_distance,
            "label": self._label(),
            "timestamp": self.timestamp,
        }

    def _label(self) -> str:
        if self.leap_distance < 0.3:
            return "🔵 Grounded extrapolation — close to known data"
        elif self.leap_distance < 0.6:
            return "🟡 Moderate leap — inference beyond known data"
        else:
            return "🟣 Creative leap — speculative, generative, not factual"


class AbductionEngine:
    """
    Generates ranked candidate hypotheses from observations.

    In a real deployment this would call an LLM in Creative Mode.
    Here we demonstrate the structure and safety framing.
    """

    def __init__(self, mode_controller):
        self.mode_controller = mode_controller
        self.history = []

    def generate(self, observations: list[str], context: str = "") -> dict:
        """
        Given observations, generate ranked candidate explanations.
        Only runs in CREATIVE or DISCOVERY mode.
        """
        from driftcore.cognition.cognitive_mode import CognitiveMode

        if self.mode_controller.mode == CognitiveMode.TRUTH:
            return {
                "status": "BLOCKED",
                "reason": "Abductive reasoning is not permitted in TRUTH MODE. Switch to CREATIVE or DISCOVERY mode.",
                "current_mode": self.mode_controller.mode.value,
            }

        # In production: call LLM here with structured prompt
        # For now: demonstrate structure with annotated placeholders
        hypotheses = self._generate_hypotheses(observations, context)

        result = {
            "status": "GENERATED",
            "mode": self.mode_controller.mode.value,
            "observations": observations,
            "context": context,
            "hypotheses": [h.to_dict() for h in hypotheses],
            "safety_label": (
                "⚠️  ALL OUTPUTS BELOW ARE SPECULATIVE. "
                "This is abductive reasoning — inference to best explanation. "
                "Do not treat as factual claims. Confidence scores are estimates."
            ),
            "timestamp": datetime.utcnow().isoformat(),
        }

        self.history.append(result)
        return result

    def _generate_hypotheses(self, observations: list[str], context: str) -> list[AbductiveHypothesis]:
        """
        Placeholder hypothesis generator.
        In production: replaced by LLM call with structured prompt.

        Prompt template for LLM integration:
        ---
        You are operating in ABDUCTIVE REASONING mode.
        Given these observations: {observations}
        Context: {context}

        Generate 3 candidate hypotheses ranked by plausibility.
        For each provide:
        - The hypothesis (one sentence)
        - Your reasoning (two sentences)
        - Confidence score (0.0-1.0)
        - Leap distance from known data (0.0=close, 1.0=far)

        Label all outputs as speculative. Never present as fact.
        Return as JSON array.
        ---
        """
        # Demonstration structure — replace with LLM in v3.1
        obs_summary = "; ".join(observations[:3]) if observations else "no observations"

        return [
            AbductiveHypothesis(
                hypothesis=f"Primary hypothesis based on: {obs_summary[:60]}...",
                confidence=0.72,
                reasoning="Most parsimonious explanation. Accounts for all observed data points.",
                leap_distance=0.25,
            ),
            AbductiveHypothesis(
                hypothesis=f"Alternative hypothesis — less likely but worth exploring.",
                confidence=0.41,
                reasoning="Requires one additional assumption. Could reveal unexpected connections.",
                leap_distance=0.55,
            ),
            AbductiveHypothesis(
                hypothesis=f"Creative leap — divergent hypothesis for discovery purposes.",
                confidence=0.18,
                reasoning="Low confidence but high generative potential. May unlock new directions.",
                leap_distance=0.85,
            ),
        ]

    def best_hypothesis(self, observations: list[str]) -> dict:
        """Return only the highest-confidence hypothesis."""
        result = self.generate(observations)
        if result["status"] != "GENERATED":
            return result
        hypotheses = result["hypotheses"]
        if not hypotheses:
            return {"status": "NO_HYPOTHESES"}
        best = max(hypotheses, key=lambda h: h["confidence"])
        return best
